-- Seed Companies
INSERT INTO companies (id, name, logo, tagline, description, website) VALUES
('86618e47-19fc-4809-9b63-956877960309', 'Linear', 'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=100&h=100&fit=crop&q=80', 'The new standard for modern software development.', 'Linear helps teams streamline software projects, sprints, tasks, and bug tracking.', 'https://linear.app'),
('9b756193-4a16-432d-907c-9b48c03792f3', 'Vercel', 'https://images.unsplash.com/photo-1614680376408-81e91ffe3db7?w=100&h=100&fit=crop&q=80', 'Develop. Preview. Ship.', 'Vercel is the platform for frontend developers, providing the speed and reliability innovators need to create at the moment of inspiration.', 'https://vercel.com');

-- Seed Jobs
INSERT INTO jobs (id, title, company_id, location, location_type, salary_range, job_type, seniority, description, responsibilities, requirements, benefits, is_featured, is_verified, apply_url) VALUES
(gen_random_uuid(), 'Senior Frontend Engineer', '86618e47-19fc-4809-9b63-956877960309', 'San Francisco, CA', 'Hybrid', '$160k - $220k', 'Full-time', 'Senior', 'Join the Linear team to build the future of software development tools.', ARRAY['Build high-performance React components', 'Optimize application state management', 'Collaborate with designers on UI/UX'], ARRAY['5+ years of React experience', 'Deep understanding of TypeScript', 'Passion for craft and UI detail'], ARRAY['Health/Dental/Vision', 'Unlimited PTO', 'Equity', 'Remote-friendly'], true, true, 'https://linear.app/careers'),
(gen_random_uuid(), 'Staff UI Engineer', '9b756193-4a16-432d-907c-9b48c03792f3', 'Remote', 'Remote', '$200k - $280k', 'Full-time', 'Lead', 'Lead the development of next-generation UI components at Vercel.', ARRAY['Architect reusable component systems', 'Drive performance improvements across the platform', 'Mentor junior engineers'], ARRAY['8+ years of frontend experience', 'Expert knowledge of CSS and web standards', 'Experience with Next.js is a must'], ARRAY['Global remote culture', 'Competitive salary', 'Home office stipend'], true, true, 'https://vercel.com/careers');
